[package]
name = "traceprism-basic-example"
version = "0.1.0"
edition = "2021"

[features]
default = ["viz"]
viz = ["dep:traceprism", "dep:serde"]

[dependencies]
traceprism = { version = "=0.1.0-preview.3", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[[bin]]
name = "basic"
path = "basic.rs"

[[bin]]
name = "binary-search"
path = "binary_search.rs"

[[bin]]
name = "abc007-c"
path = "abc007_c.rs"

[[bin]]
name = "dfs"
path = "dfs.rs"

[[bin]]
name = "serde-struct"
path = "serde_struct.rs"
